### ISSUE TITLE
how to hint DateTime field

### ISSUE THREAD

**Issue by lost22git** [IvanRublev/Nestru#4]
# code

```elixir
@derive {Nestru.Decoder, hint: %{created_at: DateTime}}
```

# error info

```shell
 ** (RuntimeError) Expected a map value received "2024-03-29T18:42:5
9.816000Z" instead. Can't convert it to a DateTime struct.
```

# expect help me do this

```elixir
|> update_in([Access.key!(:created_at)], fn prev ->
        {:ok, datetime, _tz} = DateTime.from_iso8601(prev)
        datetime
      end)
```

**Comment by IvanRublev** [comment]
Hi @lost22git , thanks for adding the issue.

This has been a challenge. I released [a new version of the library 1.0.1](https://hex.pm/packages/nestru/1.0.1), which supports serialization between structs and binaries. This eventually led to the renaming of interface functions, see the release notes in README.md. 

Here is [an example](https://github.com/IvanRublev/Nestru?tab=readme-ov-file#date-time-and-uri) how to support `DateTime` which I believe covers your case.

Please, let me know if you have any other issues!
